import type { Metadata } from "next";
import React from "react";
import "@app/styles/globals.css";

import { StudentSidebar } from "@app/pages/student/sidebar/studentSidebar";
import {
  ProfileData,
  StudentSidebarData,
} from "@/resource/students/studentSidebarData";

export const metadata: Metadata = {
  title: "OBAC-student.ac.th",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* <SidebarProvider> */}
        {/* Pass StudentSidebarData to StudentSidebar */}
        <StudentSidebar
          menuItems={StudentSidebarData.menuItems}
          profileData={ProfileData}
        />
        {children}
        {/* </SidebarProvider> */}
      </body>
    </html>
  );
}
