import "@app/styles/globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { Navbar } from "../../home/navbar";

export const metadata = {
  title: "OBAC Authentication",
  description: "Generated by FavTeam",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ToastContainer
          position="bottom-right"
          hideProgressBar
          className="z-50"
        />
        <Navbar />
        <div className="mt-32">
        {children}
        </div>
      </body>
    </html>
  );
}
